### ISSUE TITLE
new manual Page 47 layover

### ISSUE THREAD

**Issue by Jpro600k** [image-et-son/p600fw#115]
1the GliGli panel layout shown here does not exactly correspond to the synthpgrahics layover. In particular the synthgraphics layover grouped the volume A and B controls in a
”mixer” sub-panel.

overlay?

**Comment by matrix12x** [comment]
I confirm this issue in the PDF
Actual Overlay:
![](http://synthgraphics.com/images/Prophet-600/p-600fw-dt-2.jpg)

Manual page 47:
![image](https://user-images.githubusercontent.com/4423119/156689977-1c493a1e-fc53-4dc8-b6dc-5493b57e907b.png)
