### ISSUE TITLE
new manual page 48  layot ?    and the combination of commands.

### ISSUE THREAD

**Issue by Jpro600k** [image-et-son/p600fw#117]
Changing the panel layout is done by pressing button 6 in Shift Mode or Shift Lock Mode. Pressing button 6
once shows the current active layot and pressing button 6 twice (in Shift Lock Mode or holding Shift Mode)
change the panel layout.
**********
layot ?
layout ?

and

I think it is easier to understand if you describe the combination of commands.
The following description eliminates the need for the word "button" and simplifies it. 
*****
Changing the panel layout is done by pressing "FROM TAPE" and "6" in Shift Mode or Shift Lock Mode. Pressing "FROM TAPE" and "6" once shows the current active layout and pressing "6" twice (in Shift Lock Mode or holding Shift Mode)
change the panel layout.

**Comment by image-et-son** [comment]
OK, I understand - I'll make it easier to read. Note that "Shift Mode" is the same as pressing "FROM TAPE".
