### ISSUE TITLE
Knob pickup interrupts editing

### ISSUE THREAD

**Issue by RDPRDP** [image-et-son/p600fw#134]
If you have a knob in pickup mode, and don't actually seek the current value the indicator on the led will remain either pointing left or right. This is not really a problem, but if you then decide (without picking up the knob) to try and edit a parameter on the membrane panel by selecting a number, the pickup graphics interferes with the display, and you cannot do anything, except exit the mode (press TO TAPE), then enter again (press TO TAPE).

**Comment by image-et-son** [comment]
Note: the problem is not related to pick-up mode symbols. It also happens for displayed pot values, e.g. after pressing a button to select a menu parameter the last pot value is shown again.

**Comment by image-et-son** [comment]
Please check in version 15. Should be OK now.

**Comment by RDPRDP** [comment]
Yes, seems to be perfect now!
