### ISSUE TITLE
The speed at which the envelope Attack depends on the key. 

### ISSUE THREAD

**Issue by Jpro600k** [image-et-son/p600fw#141]
[program51_alpha_os14.2_Jpro600k.zip](https://github.com/image-et-son/p600fw/files/8312977/program51_alpha_os14.2_Jpro600k.zip) SYX file only program 51

[Propgram51.zip](https://github.com/image-et-son/p600fw/files/8312978/Propgram51.zip) sound example

The speed at which the envelope Attack depends on the key. 
Do you think this is a problem with a particular chip? 
I feel that because the same key speeds up. 
Will other users have the same symptoms?
I have attached a preset file.

**Comment by image-et-son** [comment]
I cannot reproduce it. But the vintage spread does affect the attack, decay and release times. I could image that if you turn it up beyond 90 it could produce that kind of difference.
