### ISSUE TITLE
2022beta1 : when I save one by one in a row ,There is a problem.

### ISSUE THREAD

**Issue by Jpro600k** [image-et-son/p600fw#151]
When I save one preset and save the next, the number in the first digit of the previous one remains displayed in the second digit, so when I save one by one in a row ,There is a problem.
Can this be fixed?
2022beta1

**Comment by image-et-son** [comment]
Thanks for posting, I'll look into it!

**Comment by matrix12x** [comment]
2022 Beta 1
I tried replicating this issue and was unable to. My button presses were as follows:
I turned on the synth. I am in preset mode.
I recalled preset 20.
I hit record 21. (to save the patch as 21)
The display displays 21.
I hit record 22. (to save the next preset as 22)
the display displays "22"

Seems ok to me.


@Jpro600k am I misunderstanding the issue?

**Comment by Jpro600k** [comment]
Check this [URL=https://drive.google.com/file/d/1_BTHWgbriALq1j3oFjx3g6blus1g3PYI/view?usp=sharing]Check this[/URL]

**Comment by matrix12x** [comment]
Thanks. yeah, I didn't get that from your description above. You didn't mention sysex or receiving patches via MIDI.

So the problem is when you receive a patches via sysex, the display shows the right digit only almost as if the left digit scrolled off the screen.

I'll try this out this weekend.

**Comment by Jpro600k** [comment]
When that happens, a similar situation may continue.
In some cases, it was normally displayed in 2 digits after normal scrolling.
The fact that the first digit is displayed in the second seg makes it look like scrolling is overkill.
There is no problem if you press the record button to return to the original mode.

**Comment by Jpro600k** [comment]
> Thanks. yeah, I didn't get that from your description above. You didn't mention sysex or receiving patches via MIDI.
> 
> So the problem is when you receive a patches via sysex, the display shows the right digit only almost as if the left digit scrolled off the screen.
> 
> I'll try this out this weekend.

Hi,Matrix12x

[preset_78_dirty_brass_Jpro600k.zip](https://github.com/image-et-son/p600fw/files/8587882/preset_78_dirty_brass_Jpro600k.zip)
[preset_00_rich_strings_Jpro600k.zip](https://github.com/image-et-son/p600fw/files/8587883/preset_00_rich_strings_Jpro600k.zip)

I prepared two preset files transferred from Prophet600 to PC.
When I created this preset, the 1's digit number was displayed in the 10's digit number.
