### ISSUE TITLE
Add option to modulate only one of the VCOs with vibrato

### ISSUE THREAD

**Issue by neodym1337** [image-et-son/p600fw#161]
One feature that was nice on the past versions was to modulate only one of the VCO's with vibrato. This was useful for example when emulating the polymoog vox humana patch. If i got it right with the new version only VCO (both vcos at the same time) or VCA is selectable

Cheers

**Comment by neodym1337** [comment]
Brilliant @matrix12x really loved that feature!

**Comment by image-et-son** [comment]
This is so simple a change, I might just sneak it into the release...

**Comment by matrix12x** [comment]
it gets my vote. lol

**Comment by image-et-son** [comment]
I've done it - it works fine. So it will be in the release - I am totally confident that it has no side effects.

**Comment by neodym1337** [comment]
Good stuff!
