### ISSUE TITLE
P600 User manual beta 2022 (2) proof read list. Chapters 1-3

### ISSUE THREAD

**Issue by tw1lh3lm** [image-et-son/p600fw#164]
Some of these are simply suggestions for clarifications. May be the result of misunderstandings on my part. Please use your judgement to ignore anything that is frivolous or incorrect. 
[P600 User Manual proof read 1-3.pdf](https://github.com/image-et-son/p600fw/files/8932729/P600.User.Manual.proof.read.1-3.pdf)

**Comment by image-et-son** [comment]
Thank you so much for the detailed review. That just added 10 EUR to the donation :-)

Side remark: "behaviour" is the correct spelling in the UK (which I learned in scholl and where I lived for many years). But I deciced to go for American. There are many more users in the US.
