### ISSUE TITLE
p600fw_User_Manual_beta_2022_.2 Page 50 Transpose

### ISSUE THREAD

**Issue by Jpro600k** [image-et-son/p600fw#168]
Overview of MIDI integration
Transpose

local on
Send MIDI Yes

It is not No.
Haven't the recent program changes been reflected yet?

**Comment by image-et-son** [comment]
The transpose event is never sent out as a MIDI event by the Prophet 600. So that seems to be OK!?

**Comment by Jpro600k** [comment]
I confirmed that it was not sent by MIDI-OX, so I will close it.
