### ISSUE TITLE
User Manual Suggested Revisions, Sections <=2

### ISSUE THREAD

**Issue by ceharris** [image-et-son/p600fw#173]
Responding to your request for proofreading of the documentation, I read up to "3 Functionality" and made notes on suggested minor fixes in the attached PDF. I wanted to make sure this workflow (using an annotated PDF) was useful before putting more time in to continue proofreading.

Thanks for all of the work on this project -- despite minor typos the documentation is excellent.

I attached two versions of the PDF. The first contains the annotations as markup. For some reason, some PDF tools don't show the annotations properly, so the second file renders the annotations as part of the content.

- [p600fw_User_Manual_beta_2022_.2.pdf](https://github.com/image-et-son/p600fw/files/9032931/p600fw_User_Manual_beta_2022_.2.pdf)
- [p600fw_User_Manual_beta_2022_.2-markup.pdf](https://github.com/image-et-son/p600fw/files/9032932/p600fw_User_Manual_beta_2022_.2-markup.pdf)

**Comment by image-et-son** [comment]
Thanks! I'll correct it (and add it to the donation list, which stood at 25 EUR before your ticket).
