### ISSUE TITLE
User Manual Suggested Revisions, Section 3

### ISSUE THREAD

**Issue by ceharris** [image-et-son/p600fw#174]
Suggested corrections and revisions for section 3 attached as marked up PDFs.

I noted many places in the text in which "e.g." (_exempli gratia_) should be replaced with "i.e." (_id est_) but I probably missed some. It's probably worth doing a global search for "e.g." and replacing it with "i.e." if what follows is intended to clarify or restate, rather than providing an example.

[p600fw_User_Manual_beta_2022_.2-section3.pdf](https://github.com/image-et-son/p600fw/files/9056585/p600fw_User_Manual_beta_2022_.2-section3.pdf)
[p600fw_User_Manual_beta_2022_.2-section3-markup.pdf](https://github.com/image-et-son/p600fw/files/9056584/p600fw_User_Manual_beta_2022_.2-section3-markup.pdf)

**Comment by image-et-son** [comment]
Thanks! I'll correct it (and add it to the donation list, which stood at 25 EUR before your ticket).
