### ISSUE TITLE
MIDI CC 45, 109, 120,122, 123 should work in any mode

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#175]
Incoming MIDI CC which correspond to patch parameters are ignore unless in preset mode. However, the MIDI CC 45/109 (arp/seq clock) as well as 120, 122 and 123 were also ignored unless in preset mode for no particular reason. These should always be applied.

**Comment by matrix12x** [comment]
CC 64 should also always be recognized

**Comment by image-et-son** [comment]
> CC 64 should also always be recognized

Absolutely. But MIDI CC 0, 1, 7 and 64 were already correctly implemented, e.g. always applied.
