### ISSUE TITLE
Add "Mix Velocity" Parameter

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#185]
This would provide even more expressivity as it changes the timbre

**Comment by matrix12x** [comment]
Great idea. Would a velocity of 64 be middle mix?
Or would this be a "bipolar" parameter where velocity below 64 subtracts and above adds?

**Comment by image-et-son** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} When I thought about it imagined the latter.                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: ***@***.***: 31 July 2022 17:24To: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [image-et-son/p600fw] Add "Mix Velocity" Parameter (Issue #185)  
Great idea. Would a velocity of 64 be middle mix?
Or would this be a "bipolar" parameter where velocity below 64 subtracts and above adds?

**Comment by image-et-son** [comment]
Add info. Same "thought trap" again: since "mix" is a parameter that affects all coices, it cannot be implemented in that way, unfortunately.
