### ISSUE TITLE
Feature Request: Add a feature to scale detune (in unison mode) over the keyboard range (Full, half, off)

### ISSUE THREAD

**Issue by matrix12x** [image-et-son/p600fw#23]
Add a feature to scale detune (in unison mode) over the keyboard range, like the filter scaling. For example, as you play up the keyboard, higher notes need less detuining in unison mode than lower pitch notes.

Could prob just use the filter scaling (full, half, off).

**Comment by image-et-son** [comment]
At the moment an absolute detune amount is added to each voice (multiplied by -3, -2, -1, 1, 2, 3) for all scales. Does the requirement mean that this amount should be scaled linearly with CV? Where should the pivot point be, e.g. the point which is unchanged by the setting at constant detune?

**Comment by matrix12x** [comment]
Pivot point should prob be middle C. I think a linear scaling should sound fine. The idea is to have a setting that sounds good on low notes not sound like too much beating on the high notes, which is a traditional issue with unison mode on synths.

**Comment by image-et-son** [comment]
From alpha 8 on detune is scaled in a fixed way (e.g. tracking amount is fixed).

**Comment by el-folie** [comment]
Sounds great now as it is with fixed tracking on "full". To my ears it´s done.

**Comment by matrix12x** [comment]
Sounds great as it is. I like how it is scaled by frequency.

**Comment by image-et-son** [comment]
OK, we'll revisit the topic in beta testing because it changes the behaviour compared to V2.0 / V21.
