### ISSUE TITLE
Sustain pedal on is not sent via MIDI

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#29]
I found one unrelated bug only now which had been there at least since 2.1rc3:
- Sustain Pedal "on" is not being sent in "Unison Track" mode. Sustain Pedal "off" is being sent though. This is true for Local On and Off modes.

**Comment by matrix12x** [comment]
in the October 26, 2013 Alphas gligli said: "Footswitch support, can be used to latch new chords in unison mode, and to hold the current arpeggio while arpeggiating."

to add the "missing sustain" in synth.c, add midi_sendSustainEvent((cur&BIT_INTPUT_FOOTSWITCH)?0:1); to the following existing routine:


	// control footswitch 
	 
	if(currentPreset.steppedParameters[spUnison] && !(cur&BIT_INTPUT_FOOTSWITCH) && last&BIT_INTPUT_FOOTSWITCH)
	{
		assigner_latchPattern();
		assigner_getPattern(currentPreset.voicePattern,NULL);
                midi_sendSustainEvent((cur&BIT_INTPUT_FOOTSWITCH)?0:1); // add this here for Midi sustain output 
	}
	else if((cur&BIT_INTPUT_FOOTSWITCH)!=(last&BIT_INTPUT_FOOTSWITCH))
	{
		if(arp_getMode()!=amOff)
		{
			arp_setMode(arp_getMode(),(cur&BIT_INTPUT_FOOTSWITCH)?0:1);
			refreshSevenSeg();
		}
		else
		{
			assigner_holdEvent((cur&BIT_INTPUT_FOOTSWITCH)?0:1);
			midi_sendSustainEvent((cur&BIT_INTPUT_FOOTSWITCH)?0:1);
		}
	}
