### ISSUE TITLE
Move "local on/off" setting from button "7" to button "0" and default preset to button "Preset"

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#36]
Button "7" doesn't work with "From Tape" held down, so can't be used for the settings menu. The setting "local on/off" must be moved somewhere else. Proposal: move to button "0" and move

**Comment by el-folie** [comment]
Move of "Local On/Off" from #7 to #0 confirmed and working.
Move of "Load Default Patch" to "Preset" button confirmed and working.
