### ISSUE TITLE
Notes held continuously when latching in unison mode  

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#55]
Bug description: switch on unison then hold a chord and latch. The last pressed note is held (never receives a note off events unless played again).

When staying in unison and doing a second (or repeated) latch, the problem does no occur - need to re-enter unison to reproduce the behaviour. Also, latch a single note does not produce the error. It is independent of the assigner priority.

**Comment by el-folie** [comment]
This one seems to be solved too, just tested and had no hanging notes in unison with multiple chord changes by pedal and latching.
