### ISSUE TITLE
Collective bug for UI navigation errors / improvable points

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#66]
1. When in record mode pressing arp buttons should cancel recording mode (like for sequencer). Currently the function sequence is odd: press record (record mode, record blinks), press arp U/D (arp U/D blinks, but overall still in record mode), press record (record goes solid, in arp hold mode), press arp U/D (arp U/D goes out, record start blinking, record mode). Open question: does the sold record LED in seq edit mode always also indicate hold mode for arp? The meaning of the record LED should be unambiguous. --> DONE

3. Press ARP up/down to start arp (Arp up/down led On), press and hold Sustain pedal (Record led turns On), press ARP up/down (to turn off arp) --> record led stays lit no matter what I press next. Can't turn it off without switching on and off P600. --> DONE
4. When in sequencer editing mode: when pressing either arp button puts the P600 into arp (non-hold) mode which overrides the keyboard input to the sequencer. It would be better to suppress that function of the arp buttons. Note: you can never go from activated arp to sequencer edit mode because the P600 goes into arp hold mode when pressing record and then pressing seq 1/2 simply starts/stops the sequencer. --> DONE
5. When in sequencer editing mode: when pressing the other seq button then this seq button also blinks and then pressing either seq button crashes the P600. It would be best to supress the other seq button in seq edit mode. --->DONE
6. Record LED blinks in Patch Management Mode (should be off) --> DONE
7. Pick-me-up spot is too tight --> DONE

**Comment by matrix12x** [comment]
I think I came across a UI bug just now, I think this is the correct spot for it, if not, let me know and I will split this off:

Parameters: in preset mode, playing any arp with any arp button pressed (up/down or random, etc). When holding the sustain pedal (arp latch) Record Led turns on (like it should), I then press the same arp button to turn arp off (but I'm still holding the sustain pedal), and here is where the issue happens: record light stays lit, no matter what, because I did not release the sustain pedal before pressing the arp button.

ex: 
Press ARP up/down to start arp (Arp up/down led On)
Press and hold Sustain pedal (Record led turns On)
Press ARP up/down (to turn off arp)
Record led stays lit no matter what I press next. Can't turn it off without switching on and off P600.

Not sure if this bug matters, I mean who besides me keeps sustain pedal held when turning off the arp. It was a fluke.

**Comment by RDPRDP** [comment]
When I try to use pickup mode many times I cannot pickup the knob, maybe the conditions are too tight? Also, I think this happens more mid sweep of a knob more than when the pickup point is at the start or end.

**Comment by image-et-son** [comment]
@RDPRDP: thanks for posting this. To nail it down I have a few questions: 1) you had this behaviour in different occasions on different dials? 2) Even very slow approach did not "pick-up" the dial? 3) Did this affect bipolar (+/-) dials specifically?

**Comment by image-et-son** [comment]
> I think I came across a UI bug just now, I think this is the correct spot for it, if not, let me know and I will split this off:
> 
> Parameters: in preset mode, playing any arp with any arp button pressed (up/down or random, etc). When holding the sustain pedal (arp latch) Record Led turns on (like it should), I then press the same arp button to turn arp off (but I'm still holding the sustain pedal), and here is where the issue happens: record light stays lit, no matter what, because I did not release the sustain pedal before pressing the arp button.
> 
> ex: Press ARP up/down to start arp (Arp up/down led On) Press and hold Sustain pedal (Record led turns On) Press ARP up/down (to turn off arp) Record led stays lit no matter what I press next. Can't turn it off without switching on and off P600.
> 
> Not sure if this bug matters, I mean who besides me keeps sustain pedal held when turning off the arp. It was a fluke.

Fixed it. I'll mark the individual point in the issue text as "DONE". I don't want to have too many small ticket flying around. Thanks for posting. It was a bug.

**Comment by matrix12x** [comment]
> When I try to use pickup mode many times I cannot pickup the knob, maybe the conditions are too tight? Also, I think this happens more mid sweep of a knob more than when the pickup point is at the start or end.

I am having the same issues. I just thought it was me and that even slowly, I may tweak too fast. Generally, I think its too tight for the speed at which I tweak the knobs (my slow). I can eventually get it, but it takes me 4 or 5 passes left and right on average.  I have this on all knobs, not just bipolar.

**Comment by RDPRDP** [comment]
> 

1. Different occaisions on different dials.
2. When I have the issue, even slow doesn't help.
3. Any knob that has pickup can have this, doesn't need to be bipolar.

I see Matrix12x has similar issue. I also sort of "sweep" the knob trying to get it to pickup, and this often works after a few times of back and forth, at slowly reducing speeds, but sometimes I cannot get a know to pickup, not matter how gentle I am with it. Of course reproducing this issue on demand is quite a challenge....  ;-)

**Comment by matrix12x** [comment]
Alpha 11
I confirm my Arp/sustain pedal bus is fixed. 
Knob pickup is way better. I like it.

**Comment by image-et-son** [comment]
I'll create a new collection for upcoming alphas
