### ISSUE TITLE
Take tuning into account for poly-mod and LFO pitch shift

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#70]
At the moment the frequency CV equivalent from poly mod and LFO is simply added to the tuned oscillator CV (see function refreshVoice() around lines 940 etc.). Variations in chip characteristics, are compensated by tuning but this is not taken into account. This leads to strongly untuned shifts. The change will affect old patches, but it is fair to assumed that almost no user has actively worked with the imperfections of this, in particular since this is also voice dependent.  Note also that the Z80 firmware takes tuning properly into account, see for example orginal preset number 5.

**Comment by image-et-son** [comment]
Horray, a new synth is born. Completely new patches are possible due to harmonic shifting. For those eager to try out: try the two patches with an older version (sounds horrible) and then with the attached release candidate 1 (sounds harmonic).
[p600firmware_v2022_RC1_20220715.zip](https://github.com/image-et-son/p600fw/files/9122173/p600firmware_v2022_RC1_20220715.zip)
[2_patches_with_harmonic_shift.zip](https://github.com/image-et-son/p600fw/files/9122179/2_patches_with_harmonic_shift.zip)

**Comment by matrix12x** [comment]
I tested both patches on the prior Beta and they don't sound too good. I updated to the version you have posted above and they sound in tune. Patch 01 sounds amazing.
