### ISSUE TITLE
Remove LFO range parameter (and rescale old patches)

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#73]

**Comment by el-folie** [comment]
Just an idea: 
Maybe the same method would be applicable to the #3 mod wheel range, where you fine-tuned the modulation onset. By reducing all those different options to one nice smooth onset and going up to max in the last third of wheel travel we could get rid of all the options to further simplify and declutter the menue for the user. (And make space for other options).

Good idea/bad idea?

**Comment by matrix12x** [comment]
I agree with @el-folie

**Comment by el-folie** [comment]
The slowest Speed on 0 is still too fast for my taste (like with a slow, nice piercing PWM by LFO). It could be like 4-5 times slower at 0 ideally.

And having the full range on the LFO freq knob is so nice for live tweaking, much much better than before!

**Comment by el-folie** [comment]
Yes, absolutely. Maybe I didn´t test that aspect earlier but yes, the onset of Speed should be really really slow to create filter resonating ambiences or slow piercing PWM sounds that travel along the brim of PWM breakup to zero.

**Comment by image-et-son** [comment]
Additional point continued in #78
