### ISSUE TITLE
Collective UI Issue for alpha 12

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#79]
1) When in preset panel mode one tweaks a knob which is not picked up, this knob is active. When switching the preset patch mode the knob is then directly applied which may lead to a sudden, unwanted change in this parameter --> DONE

2) When selecting the default patch, the P600 should definitely switch to preset (panel) mode. Otherwise the default patch is not what the user hears. --> DONE

4) When in preset patch mode (where data pot selects patch) then after using "To Tape" to change a menu parameter the pot position is directly applied and changes the program. --> DONE

5) The LED dot for negative values of bipolar pots is missing. The last time it worked as alpha 8 (!) --> DONE

**Comment by matrix12x** [comment]
Alpha 11.1 (and Alpha 10, I didn't go back and check earlier)
In Manual mode "to Tape" led never lights when "to Tape" is pressed. However, "to tape" is functioning like as if it were lit.
Is this a bug or intended?

**Comment by matrix12x** [comment]
BUG as posted in gearspace:

Jpro600K posted:
"program number set [to] 16
to tape + 77 glide 
Set value 76
Push To Tape button
Program has been changed to 76."


I confirm this bug (Alpha 11.1). 
It is not just glide.
If any "To Tape" parameter that has a numerical value is changed when in Preset mode, when "To Tape" is pressed again the preset number changes to the value of the parameter.

**Comment by image-et-son** [comment]
OK, I see. Even when fixing that (which is probably easy) I think a pick-up logic is required for the data dial for selecting patches, otherwise you'll regularly just load the patch where the data dial happens to be after you change to preset mode and touch the data dial.

**Comment by image-et-son** [comment]
Opened issue #80 for the pick-me protection of the current patch selection

**Comment by Colpocorto** [comment]
If a parameter is changed by using the classic UI, the dot is turned on, as expected. But if now you change the program with the data knob, the dot remains ON despite the newly selected program is still unaltered.

**Comment by el-folie** [comment]
Alpha12:
When switching from panel to preset mode the last used parameter value is still selectable by the Speed knob, even though To Tape hasn´t been pressed yet to select a parameter from the menue.

**Comment by matrix12x** [comment]
Alpha 12
I confirm I have the same issue as @el-folie

**Comment by Colpocorto** [comment]
I confirm #89 too (both Alpha 11 and 12).

**Comment by image-et-son** [comment]
Thanks, other point in the issue OK?

**Comment by image-et-son** [comment]
Hey 

> Alpha12: When switching from panel to preset mode the last used parameter value is still selectable by the Speed knob, even though To Tape hasn´t been pressed yet to select a parameter from the menue.

Hi, I branched off the issue #89 from this. However, when I thought about it, I think this is the desired behaviour. Please refer to #89 for this.

**Comment by image-et-son** [comment]
Number 1: TESTED, DONE
