### ISSUE TITLE
Program Change function should never be assigned to the DATA knob by default

### ISSUE THREAD

**Issue by Colpocorto** [image-et-son/p600fw#81]
Using the data/speed knob for program change is suicide for those who like me use the Prophet-600 in concerts.
If one accidentally touches the knob, or if it catches dirt and starts jumping (something that we all have experienced before with other knobs, maybe ADSR or filter), the program would change and ruin the performance.

This behaviour is ok but should be optional and never set by default.

**Comment by image-et-son** [comment]
@Colpocorto: is the patch selection by data pot sufficiently protected this way? In addition to this I could make it such that when pressing From Tape you still need to start from the current selected patch number to be able to change it.
