### ISSUE TITLE
Extended choices of frequency granularity (oct-semi, oct-free)

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#87]
The display should also indicate what the current unit of frequency dial is

**Comment by el-folie** [comment]
Also, it would be nice to have seperate settings for osc A and B, because one osc is always the "leading" stable octave setting while the second would benefit from free or semi-tone tuning in Sync or to realize intervals like 5ths, 7ths.

**Comment by image-et-son** [comment]
This is primarily about having separate settings (for A/B): free/free, semi/semi, oct/oct, semi/oct, free/oct

Would you have also oct/semi etc.?

**Comment by el-folie** [comment]
Sometimes my brain is not the fastest... (please insert facepalm smiley here)

Yes, exactly like you say: A oct - B semi, A oct - B free.

Any possible combination will make sense in a certain given situation, so if possible, all possble combinations would be nice to have.

**Comment by image-et-son** [comment]
I think that sync calls for B being on octave A being free and for many poly-mod applications it's the other way round. So: both, I guess

**Comment by el-folie** [comment]
Tested, works perfectly, done.

Great! :)
