### ISSUE TITLE
Alpha12: unison track doesn´t work for chords or one-note-unison in both preset/panel mode

### ISSUE THREAD

**Issue by el-folie** [image-et-son/p600fw#88]
Unison track only seems to switch between poly and 6-note-unison.

**Comment by matrix12x** [comment]
Alpha 12
I confirm this bug. Unison track chords are not working.
Ex: I hold down a chord and switch on Unison and a single key press should play the chord, instead a 6 voice single note plays.

**Comment by image-et-son** [comment]
I'll post a hotfix shortly

**Comment by matrix12x** [comment]
Alpha 12 hot fix:
I confirm that unison chords work, unison 1 voice works, regular unison works, and poly works

**Comment by el-folie** [comment]
alpha 12.1
I can also confirm correct behaviour again.
