### ISSUE TITLE
Parameter values no shown on display

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#90]
Edit: Actually, when selecting the VIB parameters, no values are being shown on the LCD, only when I move the Speed knob. Was it always like this? Can´t remember.

_Originally posted by @el-folie in https://github.com/image-et-son/p600fw/issues/77#issuecomment-1016952557_

**Comment by matrix12x** [comment]
Alpha12 hot fix:
I confirm it works.
Parameter values display when I hit "to tape" and a parameter number. for example 8 (detune) then the value of detune for example 03 shows.

**Comment by image-et-son** [comment]
Thanks
