### ISSUE TITLE
Top values of pots not reliably reachable

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#91]
About dynamic pot focus (if already there): Could it be that this is the reason that on faster movements the highest/lowest values of a knob are not reachable, only after turning the knob back and forth 2-3 times?

_Originally posted by @el-folie in https://github.com/image-et-son/p600fw/issues/85#issuecomment-1016887462_

**Comment by el-folie** [comment]
alpha 12.1
Confirmed: pot values top/bottom can be reached reliably again. Done.
