### ISSUE TITLE
Pitch Change after activating Glide

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#93]
When Glide = 0 and a new key is pressed and held, then turning up Glide changes the pitch of that note but no gliding effect sets in. Next notes are ok.

Also: Glide behaviour in poly mode seems a little strange, but it needs to be checked whether that has always been like that...

**Comment by el-folie** [comment]
Alpha 12.1: on my P600 it´s now like this:
When Glide = 0 and a new key is pressed and held, then turning up Glide leads to shortly pitching to the last frequency of the voices being assigned to that key and back to the note actually held. It sounds like a glitch/bug. Next notes are sounding fine with Glide being applied correctly. This is the same in unison and poly mode.

My understanding is that Glide should only have an effect on the next new note, the note being held when turning up Glide should stay stable in pitch. Would you agree?

What´s strange with Glide in poly mode? To me it seems to behave correctly generally.

**Comment by matrix12x** [comment]
Mine is doing the same as @el-folie, except, it only happens the first time I move from zero to a larger value.If I go to repeat this without recalling another patch, I cannot get the bug to repeat.

I think polyglide sounds fine.

**Comment by image-et-son** [comment]
OK, I'll need to work on the glide. I have completed the panel layout switch (GliGli vs. SCI)- that works! But then you instantly try knob performance on glide to see what that is doing. Glide is obviously not sufficiently implemented for becoming a panel control yet.

**Comment by el-folie** [comment]
Awesome that the SCI-GliGLi switch is already done and working! OMG! :)))

**Comment by matrix12x** [comment]
Alpha 13
I confirm, glide seems to work well in both SCI and GLIGLI modes
