### ISSUE TITLE
GliGli/SCI panel switch related issues

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#95]
1) Mix is set to full volume VCO B and zero volume VCO A. And since in the default preset VCO B is all waveforms "Off" you get no sound. (_Originally posted by @matrix12x in https://github.com/image-et-son/p600fw/issues/74#issuecomment-1021721421_) --> FIXED for target 13.1

2) Panel layout choice is not stored in settings for next power up --> FIXED for target 13.1

3) When loading a preset in SCI panel layout, the mix is always 0 (all OSC A) --> FIXED for target 13.1

**Comment by el-folie** [comment]
alpha 13.1:
1-3 tested and confirmed working. Done.
