### ISSUE TITLE
UI issues in alpha 13

### ISSUE THREAD

**Issue by image-et-son** [image-et-son/p600fw#96]
1) after load the default preset the vib amount and vib frequency are not updated unless the value is changed (is an unwanted side effect of performance  tuning in the code) --> FIXED for target 13.1

2) Remove "saved" message in the store procedure --> FIXED for 13.1

**Comment by el-folie** [comment]
alpha 13.1 

Bug: 
Saved scrolling message removed, but:
- first saving after power on runs fine
- from 2nd saving on strange messages appear scrolling on the LCD when saving

Proposal:
Could this be reverted to simple only Record LED flashing/no blank LCD/no scrolling?
I´m aware that some may want more info, it´s just my craving for vintage minimalism.

**Comment by image-et-son** [comment]
> alpha 13.1
> 
> Bug: Saved scrolling message removed, but:
> 
> * first saving after power on runs fine
> * from 2nd saving on strange messages appear scrolling on the LCD when saving
> 
> Proposal: Could this be reverted to simple only Record LED flashing/no blank LCD/no scrolling? I´m aware that some may want more info, it´s just my craving for vintage minimalism.

Yes, will be like that
